name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install ESP32 core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Install required libraries
        run: |
          arduino-cli lib install "PubSubClient"
          arduino-cli lib install "ArduinoJson"
          arduino-cli lib install "DHT sensor library"
          arduino-cli lib install "Adafruit Unified Sensor"

      - name: Copy config.example.h to config.h
        run: cp config.example.h config.h

      - name: Compile sketch
        run: arduino-cli compile --fqbn esp32:esp32:esp32 --output-dir /tmp/build .
